### ISSUE TITLE
TypeError: Cannot read property 'hasOwnProperty' of null

### ISSUE THREAD

**Issue by snsyzf** [thesayyn/protoc-gen-ts#31] opened 2021-02-06 13:59 UTC
D:\IdeaProjects\ml\ml-shared>npm install -g protoc-gen-ts
C:\Users\yzf\AppData\Roaming\npm\protoc-gen-ts -> C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\bin\protoc-gen-ts
npm WARN protoc-gen-ts@0.3.4 requires a peer of typescript@^4.0.2 but none is installed. You must install peer dependencies yourself.
npm WARN protoc-gen-ts@0.3.4 requires a peer of google-protobuf@^3.13.0 but none is installed. You must install peer dependencies yourself.

+ protoc-gen-ts@0.3.4
added 1 package in 0.267s

D:\IdeaProjects\ml\ml-shared>protoc-3.9.0-windows-x86_64.exe --ts_out=dist ./proto/game.proto
C:\Users\yzf\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:12449
        return array.hasOwnProperty("pos") && array.hasOwnProperty("end");
                     ^

TypeError: Cannot read property 'hasOwnProperty' of null
    at Object.isNodeArray (C:\Users\yzf\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:12449:22)
    at createNodeArray (C:\Users\yzf\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:20812:25)
    at Object.createCallExpression (C:\Users\yzf\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:22099:95)
    at Object.createCall (C:\Users\yzf\AppData\Roaming\npm\node_modules\typescript\lib\typescript.js:3022:29)
    at createToObject (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:49:14)
    at createMessage (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:1016:5)
    at processMessageDescriptor (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:1545:5)
    at processProtoDescriptor (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:1590:12)
    at main (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:1680:24)
    at Object.<anonymous> (C:\Users\yzf\AppData\Roaming\npm\node_modules\protoc-gen-ts\index.js:1765:1)
--ts_out: protoc-gen-ts: Plugin failed with status code 1.

**Comment by snsyzf** [comment] 2021-02-06 14:00
![image](https://user-images.githubusercontent.com/35677762/107120116-aa9a8a00-68c6-11eb-8611-9ec50899c3ad.png)

**Comment by NfNitLoop** [comment] 2021-02-18 22:35
This seems to be something that's broken when running against typescript versions >= 4.0.  In https://github.com/thesayyn/protoc-gen-ts/issues/32 I get similar errors if I upgrade to TSv4.

This will eventually be a breaking change that forces me to move off of protoc-gen-ts.

**Comment by thesayyn** [comment] 2021-02-18 22:38
I'm sorry that I can't look into this right now  because I don't have a computer to work on this. I  have been out of work for 2 months. So it would be great if someone could send a PR for this.

**Comment by dreamershl** [comment] 2021-03-17 14:23
I believe it is caused by this repeated field. It call with "null" parameter
![image](https://user-images.githubusercontent.com/1271739/111482552-f74b6d80-876e-11eb-9e7c-cf1b89cd6b53.png)

But here it doesn't check null (if you add elements === null, and build protobuf again, the exception won't happen again)

![image](https://user-images.githubusercontent.com/1271739/111482810-35489180-876f-11eb-8732-8a7396e12403.png)

**Comment by thesayyn** [comment] 2021-03-17 19:44
This is a great finding. I would appreciate if you can a PR to fix this. I would be happy to assist you on it and get it merged and released.

**Comment by dreamershl** [comment] 2021-03-20 04:17
have create the pull request for this fix.

**Comment by thesayyn** [comment] 2021-03-20 16:42
Thanks to @dreamershl.  A fix landed for this on master which will be released quickly.

**Closed** 2021-03-20 16:42 UTC
