### ISSUE TITLE
"deserializeBinary" do not exist in "typeof Map"

### ISSUE THREAD

**Issue by alienzhangyw** [thesayyn/protoc-gen-ts#76] opened 2021-07-22 05:54 UTC
Got ts2339 error with Map:
![image](https://user-images.githubusercontent.com/58874541/126594734-6487d0ab-413b-4097-ab5c-41a4effe556d.png)

my proto:
```
message QueryTagGroupResponse
{
  uint32 result = 1;
  string reason = 2;
  map<string, string> tag_path = 3;
}
...
rpc QueryTagsPath(stream QueryTagGroupRequest) returns (stream QueryTagGroupResponse){}
```
Maybe it's a problem of [@types/google-protobuf](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/google-protobuf/index.d.ts)?

**Comment by thesayyn** [comment] 2021-07-22 15:47
Yes, it is definitely a problem with the typings package.  it has to be fixed upstream.

**Comment by renkei** [comment] 2021-07-29 13:36
I've the same issue, without an upstream fix your package is unusable, unfortunately. There are also other `Map` related bugs in the typings package, see [#54816](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54816).

In the meanwhile, it could make sense to modify your typescript generator so that it casts the `Map` type to `any` first. The example above would then look like this:

```typescript
reader.readMessage(message, () => (pb_1.Map as any).deserializeBinary(message.tag_path, reader, reader.readString, reader.readString));
```

It's just a workaround, as long as the upstream fix isn't available. And it's safe, because the JavaScript method `jspb.Map.deserializeBinary` is really available in the google-protobuf package.

This workaround would make it possible to use your (great) package even with `Map`. What do you think?

**Comment by renkei** [comment] 2021-07-29 13:53
By the way, I've start a discussion about the missing typings for deserializeBinary: [#54824](https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54824)

**Comment by thesayyn** [comment] 2021-07-30 09:21
it makes sense that we introduce a quick fix to enable those who want to use `@types/google-protobuf` along with google-protobuf. we don’t care about typings as long as they exist in google-protobuf.

a PR is welcome

Context: we didn’t care about matching the typings of google-protobuf as it was hard to use.

**Comment by renkei** [comment] 2021-07-30 13:13
Instead of creating a PR for this project that is just a workaround for a bug in @types/google-protobuf, I've decided to create a PR for @types/google-protobuf to fix the root cause. Then this issue here should be fixed, it already works fine wiht my fork of @types/google-protobuf. Let's see, if my PR will be accepted.

**Comment by renkei** [comment] 2021-07-31 12:02
Unfortunately, it is a little bit more complicated. I had to fix the PR, so that the CI pipeline succeeds. In the PR for `@types/google-protobuf` the class Map<K, V> has this static `deserializeBinary` method now:

```typescript
class Map<K, V> {
    ...
    static deserializeBinary<K, V>(
        map: Map<K, V>,
        reader: BinaryReader,
        keyReaderFn: (reader: BinaryReader) => K,
        valueReaderFn: ((reader: BinaryReader) => V) | ((reader: BinaryReader, value: V, opt_valueReaderCallback: (value: V, reader: BinaryReader) => any) => any),
        opt_valueReaderCallback?: (value: V, reader: BinaryReader) => any,
        opt_defaultKey?: K,
        opt_defaultValue?: V
  ): void;
}
```

But now, the generated code by your package fails to compile again. The reason is, that `Map.deserializeBinary` expects a protobuf Map as first argument, but in your generated code, an ES2015 Map is passed. The Typescript compiler fails now because of the different interfaces of both Map types.

If we use the example from above, the generated code must be changed similar to this proposal in order to compile again:

```typescript
...
switch (reader.getFieldNumber()) {
    ...
    case 3: {
        // Create a temporary protobuf map
        const pbMap = new pb_1.Map<string, string>([]);

        // deserialize next key/value pair and store it in the protobuf map
        reader.readMessage(message, () => pb_1.Map.deserializeBinary<string, string>(pbMap, reader, reader.readString, reader.readString));

        // apply the new key/value pair in the ES2015 map, it's only one pair.
        pbMap.forEach((value, key) => {
            message.tag_path.set(key, value);
        });

        break;
    }

    default:
        reader.skipField();
}
```

I'm not sure, if such a change for your typescript plugin would be accepted as PR by you. Maybe I'm also missing something. A comment from you would be appreciated.

**Comment by thesayyn** [comment] 2021-08-01 07:42
You are right. We have to pass the ES6 map as any to make google protobuf happy. Even though `Map` is enough for `pb.Map` type package still wanta the same type. So we have to cast map as any then pass it to google-protobuf to make it happy. 

A PR with following changes makes sense to me

- Cast map to any whenever we pass it to google-protobuf.

**Closed** 2021-08-01 14:48 UTC

**Comment by renkei** [comment] 2021-08-11 09:01
My PR for @types/google-protobuf was accepted. It's part of 3.15.4. Now, `deserializeBinary` is known and we don't need to cast Map to `any` first. Instead, we should cast the first argument to `any` now to pass an ES2015 Map where a protobuf Map is expected. Should I create a new PR for this?

**Comment by thesayyn** [comment] 2021-08-11 09:06
That would be so sweet! 

Many thanks!!
